# Usamos una imagen base de Node.js
FROM node:18-alpine

# Establecemos el directorio de trabajo
WORKDIR /app

# Copiamos los archivos del proyecto al contenedor
COPY package*.json ./

# Instalamos dependencias
RUN npm install

# Copiamos el resto del código
COPY . .

# Exponemos el puerto de desarrollo
EXPOSE 3000

# Comando para levantar el servidor de desarrollo
CMD ["npm", "start"]
